apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: your-registry/auth:latest
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: auth-volume
              mountPath: /usr/src/app
        - name: rabbitmq-container
          image: rabbitmq
          ports:
            - containerPort: 5672
          volumeMounts:
            - name: auth-volume
              mountPath: /usr/src/app
      volumes:
        - name: auth-volume
          hostPath:
            path: /path/to/backend/apps/auth
